services:
  reverse-proxy:
    image: ghcr.io/serfriz/caddy-cloudflare-crowdsec:2
    restart: unless-stopped
    entrypoint: /entrypoint.sh
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SITE_DOMAIN=changpop.wiki
      - CROWDSEC_API_KEY_FILE=/run/secrets/crowdsec_api_key
    volumes:
      - ./entrypoint.sh:/entrypoint.sh:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - ./var/log:/log
    read_only: true
    tmpfs:
      - /tmp
    secrets:
      - crowdsec_api_key
    networks:
      chp_proxy:

networks:
  chp_proxy:
    external: true

volumes:
  caddy_data:
  caddy_config:

secrets:
  crowdsec_api_key:
    file: var/secrets/crowdsec_api_key